language: node_js
node_js:
  - "node"

branches:
  only:
    - master

cache: npm

before_deploy:
  - env:
      - NODE_ENV=production
  - npm run build && npm run package

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "build/latest_build.zip"
  skip_cleanup: true
