language: node_js
node_js:
  - '11.9.0'

branches:
  only:
    - master

cache: npm

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name Jakub Koralewski
  - git config --local user.email jakub.koralewski1@gmail.com
  - git tag -f experimental${TRAVIS_BUILD_NUMBER}
  - export NODE_ENV=development
  - npm run build
  - export NODE_ENV=production
  # - npm run dev # for testing, blocks the execution but I don't know how to make build give errors
  - npm run build
  - zip -r google-calendar-box-select-experimental${TRAVIS_BUILD_NUMBER}.zip build

deploy:
  provider: releases
  api_key: '$GH_TOKEN'
  file: google-calendar-box-select-experimental${TRAVIS_BUILD_NUMBER}.zip
  name: Experimental build $(date +'%d.%m.%Y %R UTC')
  prerelease: true
  body: This is an automagical build. Use with caution.<br/>See the build details [here](${TRAVIS_BUILD_WEB_URL}).<br/>
  skip_cleanup: true
