language: node_js
node_js:
  - '11.9.0' # stable
  - 'node' # newest


branches:
  only:
    - master

cache: npm

before_deploy:
  - git config --local user.name Jakub Koralewski
  - git config --local user.email jakub.koralewski1@gmail.com
  - git tag -f experimental${TRAVIS_BUILD_NUMBER}
  - export NODE_ENV=development
  - npm run build
  - cd build
  - zip -r google-calendar-box-select-dev-experimental${TRAVIS_BUILD_NUMBER}.zip *
  - cd ..
  - export NODE_ENV=production
  - npm run build
  - cd build
  - zip -r google-calendar-box-select-experimental${TRAVIS_BUILD_NUMBER}.zip *
  - cd ..

deploy:
  provider: releases
  api_key: '$GH_TOKEN'
  file: 
    - build/google-calendar-box-select-dev-experimental${TRAVIS_BUILD_NUMBER}.zip
    - build/google-calendar-box-select-experimental${TRAVIS_BUILD_NUMBER}.zip
  name: Experimental build $(date +'%d.%m.%Y %R UTC')
  prerelease: true
  body: This is an automagical build. Use with caution.<br/>See the build details [here](${TRAVIS_BUILD_WEB_URL}).<br/>The dev version of the extension contains source maps, console logs, etc. I recommend using it when submitting bugs.
  skip_cleanup: true
