language: node_js
node_js:
  - "node"

branches:
  only:
    - master

cache: npm

before_deploy:
  - export NODE_ENV=production
  - npm run build && zip -r latest_build.zip build

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "latest_build.zip"
  skip_cleanup: true
